# Generated by Django 5.0.3 on 2024-03-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_order_createdat_orderitem_shippingaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
